import { defineStore } from "pinia";

export const useHairCareStore = defineStore('hairCareStore', {
    state: () => ({
        ST: {
            title: 'Hair care. Средства по уходу за волосами',
            status: 'Золотой Продавец',
            conditions: `Собери полку из PSKU, соблюдая стратегию категорий, логику выкладки товаров на полке по SBD стандартам`,
            description: `У тебя в наличии весь ассортимент товаров нашего портфеля из категорий Средства по уходу за волосами (Head&Shoulders, Pantene, Pro Series, Herbal Essences). Необходимо отсортировать PSKU лист для данного типа торговой точки.  
            \nВсе SKU представлены в одном фейсе, вы можете увеличивать фейсы двойным кликом мыши (наведи на SKU и 2 раза кликни левой кнопкой мыши).`
        },
        LT: {
            title: 'Hair care. Средства по уходу за волосами',
            status: 'Золотой Продавец',
            conditions: `Собери полку из PSKU, соблюдая стратегию категорий, логику выкладки товаров на полке по SBD стандартам`,
            description: `У тебя в наличии весь ассортимент товаров нашего портфеля из категорий Средства по уходу за волосами (Head&Shoulders, Pantene, Pro Series, Herbal Essences). Необходимо отсортировать PSKU лист для данного типа торговой точки.  
            \nВсе SKU представлены в одном фейсе, вы можете увеличивать фейсы двойным кликом мыши (наведи на SKU и 2 раза кликни левой кнопкой мыши).`
        },
        OMA: {
            title: 'Hair care. Средства по уходу за волосами',
            status: 'Золотой Продавец',
            conditions: `Собери полку из PSKU, соблюдая стратегию категорий, логику выкладки товаров на полке по SBD стандартам`,
            description: `У тебя в наличии весь ассортимент товаров нашего портфеля из категорий Средства по уходу за волосами (Head&Shoulders, Pantene, Pro Series, Herbal Essences). Необходимо отсортировать PSKU лист для данного типа торговой точки.  
            \nВсе SKU представлены в одном фейсе, вы можете увеличивать фейсы двойным кликом мыши (наведи на SKU и 2 раза кликни левой кнопкой мыши).`
        },
        X2: {
            title: 'Hair care. Средства по уходу за волосами',
            status: 'Золотой Продавец',
            conditions: `Собери полку из PSKU, соблюдая стратегию категорий, логику выкладки товаров на полке по SBD стандартам`,
            description: `У тебя в наличии весь ассортимент товаров нашего портфеля из категорий Средства по уходу за волосами (Head&Shoulders, Pantene, Pro Series, Herbal Essences). Необходимо отсортировать PSKU лист для данного типа торговой точки.  
            \nВсе SKU представлены в одном фейсе, вы можете увеличивать фейсы двойным кликом мыши (наведи на SKU и 2 раза кликни левой кнопкой мыши).`
        },
        imgs: [
            {id: 1, src: './categories/hairCare/1.png', isWide: false},
            {id: 2, src: './categories/hairCare/2.png', isWide: false},
            {id: 3, src: './categories/hairCare/3.png', isWide: false},
            {id: 4, src: './categories/hairCare/4.png', isWide: false},
            {id: 5, src: './categories/hairCare/5.png', isWide: false},
            {id: 6, src: './categories/hairCare/6.png', isWide: false},
            {id: 7, src: './categories/hairCare/7.png', isWide: false},
            {id: 8, src: './categories/hairCare/8.png', isWide: false},
            {id: 9, src: './categories/hairCare/9.png', isWide: false},
            {id: 10, src: './categories/hairCare/10.png', isWide: false},
            {id: 11, src: './categories/hairCare/11.png', isWide: false},
            {id: 12, src: './categories/hairCare/12.png', isWide: false},
            {id: 13, src: './categories/hairCare/13.png', isWide: false},
            {id: 14, src: './categories/hairCare/14.png', isWide: false},
            {id: 15, src: './categories/hairCare/15.png', isWide: false},
            {id: 16, src: './categories/hairCare/16.png', isWide: false},
            {id: 17, src: './categories/hairCare/17.png', isWide: false},
            {id: 18, src: './categories/hairCare/18.png', isWide: false},
            {id: 19, src: './categories/hairCare/19.png', isWide: false},
            {id: 20, src: './categories/hairCare/20.png', isWide: false},
            {id: 21, src: './categories/hairCare/21.png', isWide: false},
            {id: 22, src: './categories/hairCare/22.png', isWide: false},
            {id: 23, src: './categories/hairCare/23.png', isWide: false},
            {id: 24, src: './categories/hairCare/24.png', isWide: false},
            {id: 25, src: './categories/hairCare/25.png', isWide: false},
            {id: 26, src: './categories/hairCare/26.png', isWide: false},
            {id: 27, src: './categories/hairCare/27.png', isWide: false},
            {id: 28, src: './categories/hairCare/28.png', isWide: false},
            {id: 29, src: './categories/hairCare/29.png', isWide: false},
            {id: 30, src: './categories/hairCare/30.png', isWide: false},
            {id: 31, src: './categories/hairCare/31.png', isWide: false},
            {id: 32, src: './categories/hairCare/32.png', isWide: false},
            {id: 33, src: './categories/hairCare/33.png', isWide: false},
            {id: 34, src: './categories/hairCare/34.png', isWide: false},
            {id: 35, src: './categories/hairCare/35.png', isWide: false},
            {id: 36, src: './categories/hairCare/36.png', isWide: false},
            {id: 37, src: './categories/hairCare/37.png', isWide: false},
            {id: 38, src: './categories/hairCare/38.png', isWide: false},
            {id: 39, src: './categories/hairCare/39.png', isWide: false},
            {id: 40, src: './categories/hairCare/40.png', isWide: false},
            {id: 41, src: './categories/hairCare/41.png', isWide: false},
            {id: 42, src: './categories/hairCare/42.png', isWide: false},
            {id: 43, src: './categories/hairCare/43.png', isWide: false},
            {id: 44, src: './categories/hairCare/44.png', isWide: false},
            {id: 45, src: './categories/hairCare/45.png', isWide: false},
            {id: 46, src: './categories/hairCare/46.png', isWide: false},
            {id: 47, src: './categories/hairCare/47.png', isWide: false},
            {id: 48, src: './categories/hairCare/48.png', isWide: false},
            {id: 49, src: './categories/hairCare/49.png', isWide: false},
            {id: 50, src: './categories/hairCare/50.png', isWide: false},
            {id: 51, src: './categories/hairCare/51.png', isWide: false},
            {id: 52, src: './categories/hairCare/52.png', isWide: false},
            {id: 53, src: './categories/hairCare/53.png', isWide: false},
            {id: 54, src: './categories/hairCare/54.png', isWide: false},
            {id: 55, src: './categories/hairCare/55.png', isWide: false},
            {id: 56, src: './categories/hairCare/56.png', isWide: false},
            {id: 57, src: './categories/hairCare/57.png', isWide: false},
            {id: 58, src: './categories/hairCare/58.png', isWide: false},
            {id: 59, src: './categories/hairCare/59.png', isWide: false},
            {id: 60, src: './categories/hairCare/60.png', isWide: false},
            {id: 61, src: './categories/hairCare/61.png', isWide: false},
            {id: 62, src: './categories/hairCare/62.png', isWide: false},
            {id: 63, src: './categories/hairCare/63.png', isWide: false},
            {id: 64, src: './categories/hairCare/64.png', isWide: false},
            {id: 65, src: './categories/hairCare/65.png', isWide: false},
            {id: 66, src: './categories/hairCare/66.png', isWide: false},
            {id: 67, src: './categories/hairCare/67.png', isWide: false},
            {id: 68, src: './categories/hairCare/68.png', isWide: false},
            {id: 69, src: './categories/hairCare/69.png', isWide: false},
            {id: 70, src: './categories/hairCare/70.png', isWide: false},
            {id: 71, src: './categories/hairCare/71.png', isWide: false},
            {id: 72, src: './categories/hairCare/72.png', isWide: false},
            {id: 73, src: './categories/hairCare/73.png', isWide: false},
            {id: 74, src: './categories/hairCare/74.png', isWide: false},
            {id: 75, src: './categories/hairCare/75.png', isWide: false},
            {id: 76, src: './categories/hairCare/76.png', isWide: false},
            {id: 77, src: './categories/hairCare/77.png', isWide: false},
            {id: 78, src: './categories/hairCare/78.png', isWide: false},
            {id: 79, src: './categories/hairCare/79.png', isWide: false},
            {id: 80, src: './categories/hairCare/80.png', isWide: false},
            {id: 81, src: './categories/hairCare/81.png', isWide: false},
            {id: 82, src: './categories/hairCare/82.png', isWide: false},
            {id: 83, src: './categories/hairCare/83.png', isWide: false},
            {id: 84, src: './categories/hairCare/84.png', isWide: false},
            {id: 85, src: './categories/hairCare/85.png', isWide: false},
            {id: 86, src: './categories/hairCare/86.png', isWide: false},
            {id: 87, src: './categories/hairCare/87.png', isWide: false},
            {id: 88, src: './categories/hairCare/88.png', isWide: false},
            {id: 89, src: './categories/hairCare/89.png', isWide: false},
            {id: 90, src: './categories/hairCare/90.png', isWide: false},
            {id: 91, src: './categories/hairCare/91.png', isWide: false},
            {id: 92, src: './categories/hairCare/92.png', isWide: false},
            {id: 93, src: './categories/hairCare/93.png', isWide: false},
            {id: 94, src: './categories/hairCare/94.png', isWide: false},
            {id: 95, src: './categories/hairCare/95.png', isWide: false},
            {id: 96, src: './categories/hairCare/96.png', isWide: false},
            {id: 97, src: './categories/hairCare/97.png', isWide: false},
            {id: 98, src: './categories/hairCare/98.png', isWide: false},
            {id: 99, src: './categories/hairCare/99.png', isWide: false},
            {id: 100, src: './categories/hairCare/100.png', isWide: false},
            {id: 101, src: './categories/hairCare/101.png', isWide: false},
            {id: 102, src: './categories/hairCare/102.png', isWide: false},
            {id: 103, src: './categories/hairCare/103.png', isWide: false},
            {id: 104, src: './categories/hairCare/104.png', isWide: false},
            {id: 105, src: './categories/hairCare/105.png', isWide: false},
            {id: 106, src: './categories/hairCare/106.png', isWide: false},
            {id: 107, src: './categories/hairCare/107.png', isWide: false},
            {id: 108, src: './categories/hairCare/108.png', isWide: false},
            {id: 109, src: './categories/hairCare/109.png', isWide: false},
            {id: 110, src: './categories/hairCare/110.png', isWide: false},
            {id: 111, src: './categories/hairCare/111.png', isWide: false},
            {id: 112, src: './categories/hairCare/112.png', isWide: false},
            {id: 113, src: './categories/hairCare/113.png', isWide: false},
            {id: 114, src: './categories/hairCare/114.png', isWide: false},
            {id: 115, src: './categories/hairCare/115.png', isWide: false},
            {id: 116, src: './categories/hairCare/116.png', isWide: false},
            {id: 117, src: './categories/hairCare/117.png', isWide: false},
            {id: 118, src: './categories/hairCare/118.png', isWide: false},
            {id: 119, src: './categories/hairCare/119.png', isWide: false},
            {id: 120, src: './categories/hairCare/120.png', isWide: false},
            {id: 121, src: './categories/hairCare/121.png', isWide: false},
            {id: 122, src: './categories/hairCare/122.png', isWide: false},
            {id: 123, src: './categories/hairCare/123.png', isWide: false},
            {id: 124, src: './categories/hairCare/124.png', isWide: false},
            {id: 125, src: './categories/hairCare/125.png', isWide: false},
            {id: 126, src: './categories/hairCare/126.png', isWide: false},
            {id: 127, src: './categories/hairCare/127.png', isWide: false},
            {id: 128, src: './categories/hairCare/128.png', isWide: false},
            {id: 129, src: './categories/hairCare/129.png', isWide: false},
            {id: 130, src: './categories/hairCare/130.png', isWide: false},
            {id: 131, src: './categories/hairCare/131.png', isWide: false},
            {id: 132, src: './categories/hairCare/132.png', isWide: false},
            {id: 133, src: './categories/hairCare/133.png', isWide: true},
            {id: 134, src: './categories/hairCare/134.png', isWide: true},
            {id: 135, src: './categories/hairCare/135.png', isWide: true},
            {id: 136, src: './categories/hairCare/136.png', isWide: true},
            {id: 137, src: './categories/hairCare/137.png', isWide: false},
            {id: 138, src: './categories/hairCare/138.png', isWide: false},
            {id: 139, src: './categories/hairCare/139.png', isWide: false},
            {id: 140, src: './categories/hairCare/140.png', isWide: false},
            {id: 141, src: './categories/hairCare/141.png', isWide: false},
            {id: 142, src: './categories/hairCare/142.png', isWide: false},
            {id: 143, src: './categories/hairCare/143.png', isWide: true},
            {id: 144, src: './categories/hairCare/144.png', isWide: true},
            {id: 145, src: './categories/hairCare/145.png', isWide: true},
            {id: 146, src: './categories/hairCare/146.png', isWide: false},
            {id: 147, src: './categories/hairCare/147.png', isWide: false},
            {id: 148, src: './categories/hairCare/148.png', isWide: false},
            {id: 149, src: './categories/hairCare/149.png', isWide: false},
            {id: 150, src: './categories/hairCare/150.png', isWide: false},
            {id: 151, src: './categories/hairCare/151.png', isWide: false},
            {id: 152, src: './categories/hairCare/152.png', isWide: false},
            {id: 153, src: './categories/hairCare/153.png', isWide: false},
            {id: 154, src: './categories/hairCare/154.png', isWide: false},
            {id: 155, src: './categories/hairCare/155.png', isWide: false},
            {id: 156, src: './categories/hairCare/156.png', isWide: false},
            {id: 157, src: './categories/hairCare/157.png', isWide: false},
            {id: 158, src: './categories/hairCare/158.png', isWide: false},
            {id: 159, src: './categories/hairCare/159.png', isWide: false},
            {id: 160, src: './categories/hairCare/160.png', isWide: false},
            {id: 161, src: './categories/hairCare/161.png', isWide: false},
            {id: 162, src: './categories/hairCare/162.png', isWide: false},
            {id: 163, src: './categories/hairCare/163.png', isWide: false},
            {id: 164, src: './categories/hairCare/164.png', isWide: false},
            {id: 165, src: './categories/hairCare/165.png', isWide: false},
            {id: 166, src: './categories/hairCare/166.png', isWide: false},
            {id: 167, src: './categories/hairCare/167.png', isWide: false},
            {id: 168, src: './categories/hairCare/168.png', isWide: false},
            {id: 169, src: './categories/hairCare/169.png', isWide: false},
            {id: 170, src: './categories/hairCare/170.png', isWide: false},
            {id: 171, src: './categories/hairCare/171.png', isWide: false},
            {id: 172, src: './categories/hairCare/172.png', isWide: false},
            {id: 173, src: './categories/hairCare/173.png', isWide: false},
            {id: 174, src: './categories/hairCare/174.png', isWide: false},
            {id: 175, src: './categories/hairCare/175.png', isWide: false},
            {id: 176, src: './categories/hairCare/176.png', isWide: false},
            {id: 177, src: './categories/hairCare/177.png', isWide: false},
            {id: 178, src: './categories/hairCare/178.png', isWide: false},
            {id: 179, src: './categories/hairCare/179.png', isWide: false},
            {id: 180, src: './categories/hairCare/180.png', isWide: false},
            {id: 181, src: './categories/hairCare/181.png', isWide: false},
            {id: 182, src: './categories/hairCare/182.png', isWide: false},
            {id: 183, src: './categories/hairCare/183.png', isWide: false},
            {id: 184, src: './categories/hairCare/184.png', isWide: false},
            {id: 185, src: './categories/hairCare/185.png', isWide: false},
            {id: 186, src: './categories/hairCare/186.png', isWide: false},
            {id: 187, src: './categories/hairCare/187.png', isWide: false},
            {id: 188, src: './categories/hairCare/188.png', isWide: false},
            {id: 189, src: './categories/hairCare/189.png', isWide: false},
            {id: 190, src: './categories/hairCare/190.png', isWide: true},
            {id: 191, src: './categories/hairCare/191.png', isWide: true},
            {id: 192, src: './categories/hairCare/192.png', isWide: true},
            {id: 193, src: './categories/hairCare/193.png', isWide: true},
            {id: 194, src: './categories/hairCare/194.png', isWide: true},
            {id: 195, src: './categories/hairCare/195.png', isWide: true},
        ]
    })
})  